[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/category"
  to = "/category"
  status = 200

[[redirects]]
  from = "/view_account"
  to = "/view_account"
  status = 200

[[redirects]]
  from = "/object"
  to = "/object"
  status = 200

[[redirects]]
  from = "/scratch/*" # Update the from path to include a wildcard for the index
  to = "/scratch/:splat" # Use :splat as a placeholder for the index
  status = 200
