import localFont from 'next/font/local';
import React from 'react';
import './_styles/globals.css';

const pretendard = localFont({ src: './_styles/fonts/PretendardVariable.woff2' });

export const metadata = {
  title: 'KRRP Info',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/favicon.ico',
  },
  // later for light-dark mode icon switch
  // icons: {
  //   icon: [
  //     {
  //       media: '(prefers-color-scheme: light)',
  //       url: '/icons/favicon.ico',
  //       href: '/icons/favicon.ico',
  //     },
  //     {
  //       media: '(prefers-color-scheme: dark)',
  //       url: '/icons/favicon.ico',
  //       href: '/icons/favicon.ico',
  //     },
  //   ],
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pretendard.className} antialiased`}>{children}</body>
    </html>
  );
}
