#!/bin/sh
commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

# Enforce commit message format
if ! echo "$commit_msg" | grep -E "^(feat|fix|test|ci|revert): "; then
  echo "Aborting commit. Commit message must start with 'feat: ', 'fix: ', 'test: ', 'ci: ', or 'revert: '."
  exit 1
fi

# Export Git hook params
export GIT_PARAMS=$*
