#!/bin/sh
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ "$current_branch" = "release" ]; then
  echo "Aborting push. Direct pushes to the 'release' branch are not allowed."
  exit 1
fi

#echo debugging the pre-push hook 1>&2
#exit 1
